### ISSUE TITLE
Very small number instead of zero in axis using eaxis

### ISSUE THREAD

**Issue by ilario** [mmaechler/sfsmisc#4]
Instead of a round zero at the zero tick in the axes I sometimes have a number like -2.775558e-17 which is clearly a glitch. With "sometimes" I mean that it depends on the range spanning from the points I'm plotting.
For example:

```
a=seq(-0.25,1.05,0.01)
plot(a, a, xaxt="n", yaxt="n")
eaxis(1)
eaxis(2)
```
![Plot with small number instead of zero label](https://user-images.githubusercontent.com/1329018/53433608-fd8a1800-39f4-11e9-9bc5-7c56ab1c5ba3.png)

Seems that it is caused by graphics::axTicks (should I try to file a bug report against it?):

```
a=seq(-0.25,1.05,0.01)
plot(a, a, xaxt="n", yaxt="n")
axTicks(1)
[1] -2.000000e-01 -2.775558e-17  2.000000e-01  4.000000e-01  6.000000e-01
[6]  8.000000e-01  1.000000e+00
axTicks(2)
[1] -2.000000e-01 -2.775558e-17  2.000000e-01  4.000000e-01  6.000000e-01
[6]  8.000000e-01  1.000000e+00
```

But somehow this does not affect base R graphics:

```
a=seq(-0.25,1.05,0.01)
plot(a,a)
```

**Comment by mmaechler** [comment]
Thank you @ilario , for the small reproducible example.

Yes, I'd claim `axTicks(1)`  to be not quite perfect .. aka a tiny bit buggy:   It is documented to provide the same "at" locations as  `axis(1)`  but does not in the case. 

As an R Core member, I've already found where in the C code  `axis()`  computes the default `at` values, namely in `CreateAtVector()` in `src/main/plot.c` ... and easy enough: It does round "small" values down to zero there.    I'd claim that `axTicks()` should do the same.

If you'd like to create a proper R bug report (on R's bugzilla, see <https://www.r-project.org/bugs.html>), I'm happy to create an account for you there if you give me your e-mail address (by e-mail rather than here;  you'll find me easily via web search "Maechler r-project.org ETH Zurich"

**Comment by ilario** [comment]
Thanks!
Here is the bug report :)
https://bugs.r-project.org/bugzilla/show_bug.cgi?id=17534

**Comment by ilario** [comment]
Fixed in R-devel [ref](https://bugs.r-project.org/bugzilla/show_bug.cgi?id=17534#c2). Thanks @mmaechler !
