### ISSUE TITLE
Use of `eval` in u.assign0 function

### ISSUE THREAD

**Issue by aviralg** [mmaechler/sfsmisc#5]
Hi! I am studying the code for this package for academic purposes. Specifically, I am interested in studying how R developers use the `eval` function. The use of `eval` in [this line](https://github.com/mmaechler/sfsmisc/blob/62a9a6a9bbbe0aea59acb2f84ea5d7a1736cae14/R/Deprecated.R#L25) caught my attention. It appears that `assign` can be called directly instead of constructing an expression and then evaluating it. 
Moreover, function name is being constructed in an obfuscated manner using `paste0("a", "ss", "ign")`.

**Comment by mmaechler** [comment]
yes, this is all on purpose, because doing it normally would trigger a "style test"  which considers all use of `assign()` as "wrong".    But here, that's desired, so the test is a FP  which I work around by this.

But then, I had *deprecated*  `u.assign0()` in 2013 ... and now defunctified it ... so the above code is gone..

**Comment by aviralg** [comment]
Thanks for the clarification.
